### ISSUE TITLE
Modules

### ISSUE THREAD

**Issue by lalli-oni** [lalli-oni/nushell-modules#12]
## Tasks
- [ ] Complete `Integrations` (hyperlinking, consider moving into module sections)
- [ ] Complete `Installation instructions` (missing prerequisite nushell setup, selecting modules)
- [ ] Add scripts to modules
- [ ] Look into sourcing module/script documentation from `.nu` files
