### ISSUE TITLE
Page improvements

### ISSUE THREAD

**Issue by lalli-oni** [lalli-oni/nushell-modules#13]
## Tasks
- [ ] Default route matching
- [ ] Investigate sub routing (fx. modules/testing)
- [ ] Extract page contents (import each page into `index.html`)
- [ ] Organise stylesheets
- [ ] Add link to GH repo

**Comment by lalli-oni** [comment]
Looking into route matching. Using `:target` means the url hash has to match an elements unique `id`.

The main problem is the anchors not being highlighted when its route is matched.

Researching, I came across this proposed css psuedo-class that seems to solve this issue, at least for anchors..
