### ISSUE TITLE
tasks

### ISSUE THREAD

**Issue by lalli-oni** [lalli-oni/nushell-modules#9]
Parent task: #4 

# tasks
⚠️  Unprioritised and uncommited.
- [x] Return structured data
- [X] Add `--format` flag to return pretty printed table
- [ ] Rough performance requirements (fx. must run consistently under 5sec.)
- [ ] Code formatting (line breaks, commenting, general best practices)
- [x] Move `relative-age` somewhere more fitting
- [X] Show if `@me` made last comment
- [X] Use structured data for comments
- [X] 🐛 Remove system discussion from comments
- [ ] GitHub integration
- [ ] JIRA integration
- [X] Extract `TODO` comments from code into Issues
- [ ] 🐛 Does not work when remote repo name does not match folder name
- [ ] 🐛 When not in a git repo we just print the internal git error msg
- [ ] Make jira and gitlab id columns hyperlinks in `--format`
- [ ] Use JIRA as the starting point
- [ ] 🐛 Tasks in jira without a MR are not shown
- [ ] 🐛 Tasks not in the same repository are not shown

# prune-branches
- [X] Select merged branches for deletion
- [X] Select local orphan branches (not exists in remote) for deletion
- [ ] When confirming local orphan branch deletion: show unmerged commits
